dfgdfg

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,5 +1,10 @@
-if [ $(git rev-parse HEAD) != $(git rev-parse origin/$(git rev-parse --abbrev-ref HEAD)) ]; then
-  echo "Ваша ветка не синхронизирована с удалённой. Нужно сделать git pull."
-else
-  echo "Ваша ветка актуальна."
+#!/bin/sh
+branch=$(git rev-parse --abbrev-ref HEAD)
+echo "Pulling latest changes from origin/$branch"
+git pull origin $branch
+
+# Проверяем, успешно ли выполнен git pull
+if [ $? -ne 0 ]; then
+  echo "Error pulling latest changes. Aborting commit."
+  exit 1
 fi
